export const CODE_SUBMITTED = 'CODE_SUBMITTED';
export const CODE_VALID = 'CODE_VALID';
export const CODE_INVALID = 'CODE_INVALID';

export const REGISTRATION_SUBMITTED = 'REGISTRATION_SUBMITTED';
export const REGISTRATION_VALIDATION_REQUIRED = 'REGISTRATION_VALIDATION_REQUIRED';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_VALIDATION_FAILED = 'REGISTRATION_VALIDATION_FAILED';
